#!/usr/bin/env bash

set -e
set -x


mypy pybotx_smartapp_smart_logger tests
flake8 pybotx_smartapp_smart_logger tests

black --check pybotx_smartapp_smart_logger tests --diff
isort --recursive --check-only pybotx_smartapp_smart_logger tests
